server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /vk-user

spring:
  application:
    name: vk-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    hikari:
      connection-timeout: ${JDBC_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${JDBC_IDLE_TIMEOUT:600000}
      max-lifetime: ${JDBC_MAX_LIFE_TIME:1800000}
      minimum-idle: ${JDBC_MIN_IDLE:16}
      maximum-pool-size: ${JDBC_MAX_POOL_SIZE:16}
  jpa:
    hibernate:
      ddl-auto: update

redis:
  database: ${REDIS_DB:0}
  host: ${REDIS_HOST:127.0.0.1}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  connection:
    max.total: ${REDIS_CONNECTION_TOTAL:100}
    max.idle: ${REDIS_CONNECTION_MAX_IDLE:100}
    min.idle: ${REDIS_CONNECTION_MIN_IDLE:30}

kafka:
  broker: ${KAFKA_BROKER:}


jwt:
  expire-time: ${JWT_EXPIRE_TIME:}
  signing:
    key: ${JWT_KEY:}




